module Spark

export
    SparkConfig,
    SparkContext,
    RDD,
    JuliaRDD,
    JavaRDD,
    text_file,
    parallelize,
    map,
    map_pair,
    map_partitions,
    map_partitions_pair,
    map_partitions_with_index,
    reduce,
    filter,
    collect,
    collect_to_arrow,
    collect_to_tuples,
    collect_to_dataframe,
    count,
    id,
    num_partitions,
    close,
    @attach,
    share_variable,
    @share,
    flat_map,
    flat_map_pair,
    cartesian,
    group_by_key,
    reduce_by_key,
    cache,
    repartition,
    coalesce,
    pipe,
    # SQL
    SparkSession,
    Dataset,
    sql,
    read_json,
    write_json,
    read_parquet,
    write_parquet,
    read_df,
    write_df,
    checkpoint,
    local_checkpoint,
    to_json,
    explain,
    create_df,
    create_or_replace_temp_view,
    create_temp_view
    
    

include("core.jl")

end 
